### ISSUE TITLE
Trying to use the Proxy for a POST request

### ISSUE THREAD

**Issue by sfossum** [twitchax/AspNetCore.Proxy#52]
I am trying to pass a POST request through the Proxy but get a statuscode 502 Bad Gateway.

Is there anything special that needs to be done to setup the Proxy for a POST request. The mapping is basically like what we use for the GET which works with out issues.

**Comment by szalapski** [comment]
I do believe that a POST request just works, even on a `Map()` configuration.  Was there maybe some other issue that we resolved already?

**Comment by twitchax** [comment]
@sfossum, can you paste the relevant code?  The number one problem I see with POST requests is caused by reading the `RequestBody`, usually by using `[FromBody]`, or something like that.

Reading the request body before it is passed to the proxier causes the body to be fully consumed, so proxying usually fails.

**Comment by sfossum** [comment]
I have been able to get it working. I am not sure what was done to make it work. It just started working. 
  Thanks for the replys.
